### PR TITLE
show icons in RepoTree

### PR DESCRIPTION
**Pull request by antis81**
Let's add a little more color :rainbow: to the otherwise boring repository view.

### CODE REVIEW

**Comment by antis81** [comment]
together with the new icons looks like this:
mgv_repo_history_view

**Comment by scunz** [comment]
@antis81, this is really nice, but there's a big big **BUT**:

Can we somehow optimise the height ratio between the icons and the texts, ideally approaching a value of 1?

**Comment by antis81** [comment]
@scunz, you mean like this ...
repotree_24pt

The first sample uses a font size of 24pt (pixelSize() again returns -1 - strange...). The second sample uses a font size of 11pt. I also introduced a minimum icon size of fixed 16px. This is what we see here:
repotree_11pt

Ok?

**Comment by scunz** [comment]
Yeah, exactly. But note, that it has to match whatever the user chooses to setup... Would be funny to force the "Fontsize" to be a compile time setting :)

**Pull request merged**
