### PR TITLE
finalization of welcome screen for v0.1

### PR DESCRIPTION
**Pull request by antis81**
- [x] final version of background image (@claus007: peaceful reminder :smile:)
- [x] transparent background image
- [x] fixed image to bottom right (even when resizing the viewport smaller than the bg image)

### CODE REVIEW

**Comment by scunz** [comment]
@antis81, @claus007 Whatever image will finally make it, I think that it should be included in source format, too. That is probably svg here, right?

**Comment by antis81** [comment]
It's actually Blender format (a .blend text file). Maybe it makes sense to add a submodule containing that :question:.

**Comment by scunz** [comment]
No submodule, just put the image source alongside the final image, so it stays reproducible.

**Comment by scunz** [comment]
:+1: :page_facing_up: :100:

**Pull request merged**
